replicaCount: 1

image:
  repository: docker.io/jhonatas17/simpleblogger
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env: [] 

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api.devopsbr.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-devopsbr-com-tls
      hosts:
        - api.devopsbr.com
